---
title: "02-arrangeGraphs"
author: "Thomas Gredig"
date: "04/10/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Arrange Graphs

This shows you how to arrange your graphs:

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(showtext)
library(ggtext)
library(patchwork)
font_add_google("Roboto Condensed", "roboto condensed")


getData <- function(x1) {
  data.frame(x=1:100, y=x1+runif(100,min=0, max=10))
}
```

## First Plot

```{r}
basic_plt <- function(x) {
  q = getData(x) 
  q %>% ggplot(aes(x,y)) + 
    geom_point(col='red', size=1.5) +
    geom_point(col='white', size=0.5, alpha=0.4) + 
    scale_y_continuous(limits = c(0,20)) + 
    theme_bw()
}
plt_list = lapply(c(0,5,10), basic_plt)
```

```{r show_figure, fig.width = 9, fig.height = 3}
plt_row <- plt_list[[1]] + plt_list[[2]] + plt_list[[3]] + plot_layout(nrow = 1)
plt_row
```


```{r}
spacer <- ggplot() +
  labs(title = "The graphs are arranged in 3 columns and two\nrows.") +
  theme_void() +
  theme(plot.title = element_text(family = "roboto condensed", size = 12, margin = margin(15,0,5,0), color =  "#183170", hjust = 0),)

final <- plt_row / spacer / plt_row +
  plot_layout(heights = c(1, 0.1, 1))+ 
  plot_annotation(
      title = "3 Random Graphs",
      subtitle = str_wrap("Each graph is offset by a different amount.", 120),
      caption = "#graphRepo | author: Thomas Gredig",
      theme = theme(
        plot.title = element_text(family = "oswald", size = 14, color = "#183170", hjust = 0.5, face = "bold", margin = margin(10,0,10,0)),
        plot.subtitle = element_textbox_simple(family = "roboto condensed", color = "#183170", size = 12, halign = 0.5),
        plot.caption = element_text(color = "blue", size = 10, hjust = 0.98)      
      )
    )


ragg::agg_png(here::here("render", paste0("02-arrangeGraphs", format(Sys.time(), "%Y%m%d"), ".png")), res = 300, width = 6, height = 4, units = "in")
final
  
dev.off()

```